version: "3.9"
services:
  nginx:
    build:
      context: .
      target: nginx
      args:
        FASTCGI_PASS_HOST: "php"
    ports:
      - "8383:8080"
    volumes:
      - "./nginx/default.conf.template:/etc/nginx/templates/default.conf.template"
      - "./api/static:/var/www/html/static"
  
  php:
    build:
      context: .
      target: php
    volumes:
      - "./api:/var/www/html"
  
  frontend:
    build:
      context: .
      target: frontend
#    command: sh -c 'npm install && npm run dev'
    command: sh -c 'sleep 10000'
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/var/www/html"
