version: "3.9"
services:
  nginx:
    build:
      context: .
      target: nginx
      args:
        FASTCGI_PASS_HOST: "php"
        WEBSOCKET_SERVER: "php"
    ports:
      - "8383:8080"
    volumes:
      - "./infrastructure/nginx/default.conf.template:/etc/nginx/templates/default.conf.template"
  
  php:
    build:
      context: .
      target: php
    volumes:
      - "./api:/var/www/html"
    ports:
      - "8082:8080"
  
  frontend:
    image: node:19-alpine
    command: sh -c 'npm install && npm run dev'
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/var/www/html"
