version: "3.9"
services:
  nginx-prod:
    build:
      context: .
      target: nginx-prod
      args:
        FASTCGI_PASS_HOST: "php-prod"
    ports:
      - "8384:8080"

  php-prod:
    build:
      context: .
      target: php-prod

  frontend-prod:
    build:
      context: .
      target: frontend
    tty: true