version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8383:80"
    volumes:
      - "./api/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./api:/var/www/html"
  php:
    image: php:8.1-fpm-alpine
    volumes:
      - "./api:/var/www/html"
  frontend:
    image: node:19-alpine
    command: sh -c 'npm install && npm run dev'
    working_dir: "/var/www/html"
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/var/www/html"