# fly.toml file generated for kudosgen-phpfpm on 2023-01-02T16:30:39+02:00

app = "kudosgen-php"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[build]
  build-target = "php-prod"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.tcp_checks]]
    interval = "5s"
    restart_limit = 2
    timeout = "2s"
  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
  [[services.ports]]
    handlers = ["http"]
    port = "8080"

[[services]]
  internal_port = 9000
  protocol = "tcp"
  [[services.tcp_checks]]
    interval = "5s"
    restart_limit = 2
    timeout = "2s"
